Partially revert "Convert sync-dir and sync-file to python"
This partially reverts commit 28a4f0efa2 / change I5ab7b2fba, restoring
sync-dir, sync-file, and sync-common-file to the shell script versions.
The new version didn't work for Sean Pringle when he attempted to sync a change
to the database manifest (he was able to use these old scripts). I wasn't able
to reproduce the issue, but it's safest to simply revert this for now until
Bryan can look at this in detail.

The docs/scripts.rst changes are required to make Jenkins happy; otherwise it
tries to invoke "sync-dir/sync-file --help" so that it can interpolate the
output into the generated documentation.

Change-Id: I449eba1bc6ea1783d2978c58ae75d7cf592f94ad

diff --git a/bin/sync-dir b/bin/sync-dir
--- a/bin/sync-dir
+++ b/bin/sync-dir
@@ -1,17 +1,28 @@
-#!/usr/bin/env python
-# -*- coding: utf-8 -*-
-#
-# Synchronize a directory from common/ to the cluster.
-#
-# Copyright © 2014 Wikimedia Foundation and contributors
+#!/bin/bash
+## synchronizes a directory from common/ on all apaches
 
-import os
-import sys
+. /usr/local/lib/mw-deployment-vars.sh
+BINDIR=/usr/local/bin
 
-# Add scap package to search path
-script = os.path.realpath(sys.argv[0])
-scap_src = os.path.dirname(os.path.dirname(script))
-sys.path.append(scap_src)
+[ $# -lt 1 ] && {
+	echo >&2 "Usage: sync-dir directory [message]"
+	exit 1
+}
 
-import scap
-scap.SyncDir.run()
+FILE=$1
+shift
+
+# Sanity check
+if [ ! -d "$MW_COMMON_SOURCE/$FILE" ]; then
+	echo >&2 "Target file is not a directory"
+	exit 1
+fi
+
+# Perform syntax check
+$BINDIR/lint $MW_COMMON_SOURCE/$FILE || {
+	echo >&2 "Aborted due to syntax errors"
+	exit 1
+}
+
+# Actually sync the dir...
+$BINDIR/sync-common-file $FILE "$@"
diff --git a/bin/sync-file b/bin/sync-file
--- a/bin/sync-file
+++ b/bin/sync-file
@@ -1,17 +1,28 @@
-#!/usr/bin/env python
-# -*- coding: utf-8 -*-
-#
-# Synchronize a file from common/ to the cluster.
-#
-# Copyright © 2014 Wikimedia Foundation and contributors
+#!/bin/bash
+## synchronizes a single file from common/ on all apaches
 
-import os
-import sys
+. /usr/local/lib/mw-deployment-vars.sh
 
-# Add scap package to search path
-script = os.path.realpath(sys.argv[0])
-scap_src = os.path.dirname(os.path.dirname(script))
-sys.path.append(scap_src)
+BINDIR=/usr/local/bin
 
-import scap
-scap.SyncFile.run()
+[ $# -lt 1 ] && {
+	echo >&2 "Usage: sync-file file [message]"
+	exit 1
+}
+
+FILE=$1
+shift
+
+# Sanity check
+if [ -d "$MW_COMMON_SOURCE/$FILE" ]; then
+	echo >&2 "Target file is a directory, not a single file"
+	exit 1
+fi
+
+# Perform syntax check
+php -l $MW_COMMON_SOURCE/$FILE || {
+	echo >&2 "Aborted due to syntax errors"
+	exit 1
+}
+
+$BINDIR/sync-common-file $FILE "$@"
