perform-release: Add GitLab support
Bug: T321847

diff --git a/release-scripts/perform-release b/release-scripts/perform-release
--- a/release-scripts/perform-release
+++ b/release-scripts/perform-release
@@ -5,6 +5,10 @@ set -eu -o pipefail
 # Don't set this
 SKIP_CHECKS=${SKIP_CHECKS:-}
 
+BRANCH=master
+
+SCRIPTDIR="$(dirname "$0")"
+
 function get_last_tag {
     git tag --sort version:refname | grep -v debian/ | tail -1
 }
@@ -34,8 +38,23 @@ function assert_clean_checkout {
     fi
 }
 
-function wait_for_merge {
-    local change_number="$1"
+function sanity_checks {
+    assert_clean_checkout
+    git pull --rebase
+    assert_clean_checkout
+    if [ "$(git rev-list origin/$BRANCH..)" ]; then
+        echo Local commits detected:
+        git log --oneline origin/$BRANCH..
+        echo Aborting
+        exit 1
+    fi
+}
+
+function push_gerrit {
+    git push origin HEAD:refs/for/$BRANCH%l=Code-Review+2 &> "$tmp"
+
+    local change_number
+    change_number=$(grep mediawiki/tools/scap/+ "$tmp" | sed -r -e 's,^.*mediawiki/tools/scap/\+/([0-9]+).*$,\1,')
 
     echo -n "Waiting for change $change_number to merge..."
 
@@ -62,14 +81,54 @@ function wait_for_merge {
     done
 }
 
-function sanity_checks {
-    assert_clean_checkout
-    git pull --rebase
-    assert_clean_checkout
-    if [ "$(git rev-list origin/master..)" ]; then
-        echo Local commits detected:
-        git log --oneline origin/master..
-        echo Aborting
+function push_gitlab {
+    local remote_branch="review/$USER/release-$VERS"
+
+    git push \
+        -o merge_request.create \
+        -o merge_request.target=$BRANCH \
+        -o merge_request.merge_when_pipeline_succeeds \
+        -o merge_request.remove_source_branch \
+        origin "HEAD:$remote_branch" &> "$tmp"
+
+    local mr_id
+    mr_id=$(grep /merge_requests/ "$tmp" | sed -r -e 's,^.*/merge_requests/([0-9]+).*$,\1,')
+
+    echo -n "Waiting for merge request $mr_id to merge..."
+
+    while true; do
+        echo -n "."
+        curl -sSf "https://gitlab.wikimedia.org/api/v4/projects/repos%2freleng%2fscap/merge_requests/$mr_id" > "$tmp"
+
+        local state status
+        state="$(jq -r .state "$tmp")"
+        status="$(jq -r .merge_status "$tmp")"
+
+        if [ "$state" == "merged" ]; then
+            echo
+            echo "Merge request $mr_id has been merged"
+            return 0
+        fi
+        if [[ "$status" =~ cannot ]]; then
+            echo
+            echo "Merge request $mr_id can't be merged"
+            exit 1
+        fi
+
+        sleep 5
+    done
+}
+
+function get_origin_type {
+    local url
+    url=$(git remote get-url origin)
+
+    if [[ "$url" =~ gitlab ]]; then
+        echo gitlab
+    elif [[ "$url" =~ gerrit ]]; then
+        echo gerrit
+    else
+        echo "$0: Unsupported origin url: $url" 1>&2
         exit 1
     fi
 }
@@ -89,17 +148,15 @@ fi
 
 echo "Selected version $VERS"
 
-release-scripts/prepare-scap-release "$VERS"
+"$SCRIPTDIR/prepare-scap-release" "$VERS"
 
 tmp="$(mktemp)"
 trap 'rm -f $tmp' EXIT
 
+origin_type=$(get_origin_type)
+
 echo Pushing commit
-git push origin HEAD:refs/for/master%l=Code-Review+2 &> "$tmp"
-
-change_number=$(grep mediawiki/tools/scap/+ "$tmp" | sed -r -e 's,^.*mediawiki/tools/scap/\+/([0-9]+).*$,\1,')
-
-wait_for_merge "$change_number"
+"push_${origin_type}"
 
 git pull --rebase
 
